### ISSUE TITLE
missing comparison overloads

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple#13]
Do you intend for the tuple header to provide comparison operator overloads?  Or should users just provide them?

I'm about them to implement them and can do a PR.   Now that tie (and related issues with tuples of references interacting with tuples of values), I think that Thrust with the new, non-recursive, variadic tuple should be working once these operators are added.

**Comment by andrewcorrigan** [comment]
Does it matter if they are member or free functions?

**Comment by jaredhoberock** [comment]
To the degree possible, I intend for it to implement the contents of S 20.4 of the C++11 standard. It looks like the relational operators are free functions. If you want to do it and submit a PR, that'd be great.

**Comment by andrewcorrigan** [comment]
Resolved in my PR.
