### ISSUE TITLE
cannot compile with CUDA 7.0 RC on CentOS 7 (gcc 4.8)

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple#17]
When I compile my branch of Thrust using this tuple with CUDA 7.0 RC on CentOS 7 I get the following error.

```
internal error: assertion failed at: thrust/thrust/detail/tuple/variadic_tuple.h(395): "/dvs/p4/build/sw/rel/gpu_drv/r346/r346_00/drivers/compiler/edg/EDG_4.9/src/expr.c", line 3108
```

That is referring to the line

```
               (sizeof...(Types) == sizeof...(UTypes)) &&
```

in the constructor:

```
    template<class... UTypes,
             class = typename std::enable_if<
               (sizeof...(Types) == sizeof...(UTypes)) &&
               __tuple_and<
                 std::is_constructible<Types,UTypes&&>...
               >::value
             >::type>
    __TUPLE_ANNOTATION
    explicit tuple(UTypes&&... args)
      : base_{std::forward<UTypes>(args)...}
    {}
```

I wrote a simple test code that invokes this constructor, but cannot reproduce this compiler crash independent of my large code.    Jared, I wonder if you have any ideas?  I imagine if I send this to the compiler team they would not be able to reproduce the crash.

**Comment by jaredhoberock** [comment]
It's just a compiler crash -- who knows why they happen. You should file a bug against the compiler.

**Comment by andrewcorrigan** [comment]
Thanks anyway.  I'll let you know if/when they fix it.  Hopefully they do, since this is a showstopper for using variadic tuple on Linux with CUDA.

**Comment by jaredhoberock** [comment]
Sometimes a compiler will crash on invalid input, so there may be some subtle error in that constructor. You may be able to find some other way to write that constructor to workaround the crash.

**Comment by andrewcorrigan** [comment]
I've been trying, but have not found an equivalent workaround.  In my opinion, it seems unlikely that the constructor itself is at fault:
1. I invoked that constructor in other contexts.  Not only did the code compile with nvcc on Linux, it ran fine too.
2. It compiles and runs with clang++ and g++.  It also works fine with CUDA, as long as it's on the Mac, and not Linux.  
3. It crashes with the exact same internal compiler error using Intel C++ 15, which apparently also uses EDG for its frontend.

By the way, I did manage to come up with a simple reproducer -- if you create a zip_iterator which dereferences to nested tuples, than this internal compiler error is triggered.

**Comment by andrewcorrigan** [comment]
For the record, the NVIDIA compiler team has now reproduced this issue locally and are working on a fix.

**Comment by jaredhoberock** [comment]
If you give me the nvbug # for your issue, I can follow it from my end.

**Comment by andrewcorrigan** [comment]
1608271

**Comment by andrewcorrigan** [comment]
Your compiler team has fixed this in CUDA 7.5.  And they suggested a workaround.  I am opening a PR in this regard.

**Comment by andrewcorrigan** [comment]
The workaround would be to add something like:

```
#if (defined(__CUDA_ARCH__) && CUDA_VERSION <= 7000) && (defined(__GNUC__) && !defined(__clang__))
template <class T, class... Args>
struct std__is_constructible : std::integral_constant<bool,__is_constructible(T, Args...)> { };
#else
template <class T, class... Args>
struct std__is_constructible : std::is_constructible<T, Args...> { };
#endif
```

at the top and then replace `std::is_constructible` with `std__constructible` everywhere.

It's pretty ugly, would you actually be interested in a PR for this?  Or perhaps you already have access to the version that has the bug fix.

**Comment by jaredhoberock** [comment]
Thanks Andrew, I've followed the bug. I've not encountered the problem so I'd rather not propagate the workaround -- CUDA 7.5 will be here soon enough :-)
