### ISSUE TITLE
destructor cannot be marked constexpr

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple#30]
When I compile with AppleClang 6.1.0 (3.6.0 svn) in C++14 mode I receive an error that: `destructor cannot be marked constexpr`, referring to:

```
    __TUPLE_ANNOTATION
    ~__tuple_leaf_base() = default;
```

When compiling on the host, if I simply comment out `__TUPLE_ANNOTATION` it proceeds to compile fine, with everything else marked `constexpr`.  That's not a solution since we need the `__device__ __host__` decorators with CUDA.

I see that you need the destructor to be explicitly declared for #25.  

It seems to me that there needs to be an additional __TUPLE_ANNOTATION_DESTRUCTOR defined, that does not involve constexpr.

**Comment by jaredhoberock** [comment]
It seems like it would be simpler to just eliminate that destructor. I tried it within Agency and there were no complaints.

**Comment by andrewcorrigan** [comment]
Thanks.

I assumed that it was necessary to have `#pragma nv_exec_check_disable` with CUDA, but if not then even better.
