### ISSUE TITLE
inefficient storage scheme

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple#8]
I understand that the precise memory layout of tuple is an implementation detail, however I believe that a template specialization is needed to avoid storing tail as `tuple<>` in `tuple<T>`.  I compared your `tuple`'s size (in namespace `thr`) with that of `std::tuple` (from libc++).  

```
sizeof(thr::tuple<>): 1
sizeof(std::tuple<>): 1
sizeof(thr::tuple<int>): 8
sizeof(std::tuple<int>): 4
sizeof(thr::tuple<int,int>): 12
sizeof(std::tuple<int,int>): 8
sizeof(thr::tuple<int,int,int>): 16
sizeof(std::tuple<int,int,int>): 12
sizeof(thr::tuple<int,int,int,int>): 20
sizeof(std::tuple<int,int,int,int>): 16
```

It gets worse with nesting -- in this case twice the storage as compared to libc++ is consumed!

```
sizeof(thr::tuple<int,thr::tuple<int>>): 16
sizeof(std::tuple<int,std::tuple<int>>): 8
sizeof(thr::tuple<int,thr::tuple<int,thr::tuple<int>>>): 24
sizeof(std::tuple<int,std::tuple<int,std::tuple<int>>>): 12
sizeof(thr::tuple<int,thr::tuple<int,thr::tuple<int,thr::tuple<int>>>>): 32
sizeof(std::tuple<int,std::tuple<int,std::tuple<int,std::tuple<int>>>>): 16
```

I think the solution is to just specialization for `thrust::tuple<T>`, which lacks a `tuple<> tail_`.

**Comment by andrewcorrigan** [comment]
BTW, I am using tuple from agency, which appears to use the same storage scheme (but actually supports nesting.)

**Comment by jaredhoberock** [comment]
Alternative may be to derive from the tail so the compiler can use the zero size base class optimization.

**Comment by andrewcorrigan** [comment]
It's up to you, of course.

I have embedded agency's tuple into my variadic branch of Thrust (and it's working by the way!).  I implemented the specialization for I mentioned above, and everything is compiling.  Just about to start testing it at runtime.

**Comment by andrewcorrigan** [comment]
it looks like the new implementation fixes this.  Perhaps a check could be added to demo.cpp to enforce/demonstrate this?

```
  static_assert(sizeof(foo::tuple<int,int>) == sizeof(int)*2, "sizeof");
  static_assert(sizeof(foo::tuple<int,foo::tuple<int>>) == sizeof(int)*2, "sizeof");
```

**Comment by jaredhoberock** [comment]
I don't think there's any way to ensure the size of a type won't be greater than the sum of its members:

```
#include <tuple>
#include <iostream>

int main()
{
  std::cout << "sizeof(tuple<char,double>): " << sizeof(std::tuple<char,double>) << std::endl;
  return 0;
}
```

```
$ g++ -std=c++11 -Iinclude sizeof.cpp 
$ ./a.out 
sizeof(tuple<char,double>): 16
```
