### ISSUE TITLE
recursive vs. non-recursive implementation

### ISSUE THREAD

**Issue by andrewcorrigan** [jaredhoberock/tuple#9]
While learning about `std::tuple`, I came across [this](http://stackoverflow.com/questions/9641699/why-is-it-not-good-to-use-recursive-inheritance-for-stdtuple-implementations).

I wonder if you had considered using a non-recursive implementation?

I am embedding your variadic tuple into Thrust.  Compile-time is a huge problem for me already in my tuple-laden, Thrust-based code (it takes ~30 mins with CUDA, 2-3 minutes with GCC, ~1 minute with LLVM), so anything that could be done to speed up compilation of code using tuple is of major consequence.

**Comment by jaredhoberock** [comment]
That blows. Yes, I've noticed that EDG-based compilers have trouble with this codebase. Unfortunately The libcxx implementation looks really complicated and I don't have time at the moment to swap out the implementation.

**Comment by andrewcorrigan** [comment]
If the implementation in libcxx is too complicated, then what about basing it off of [this implementation](https://bitbucket.org/mitchnull/samples/src/tip/cpp/Tuple/Tuple.hpp), described in [this tutorial](http://mitchnull.blogspot.com/2012/06/c11-tuple-implementation-details-part-1.html)?

I'd be happy to pursue implementing a non-recursive tuple if that is what ultimately would solve my compilation speed issues.  However, I would also prefer to take the approach that would be most likely to get incorporated into agency and/or thrust, otherwise I am wasting my time.

**Comment by andrewcorrigan** [comment]
Also, when I try to compile my code using your Thrust with variadic tuple, I run out of memory on my Mac and it goes into swap memory and never completes, and then on my RHEL7 system, with gcc 4.8.2, it stops with an internal EDG error in one of the variadic tuple constructors.

**Comment by andrewcorrigan** [comment]
The implementation is recursive now, correct?  I guess this issue can be closed?

As for my code, it still takes about the same memory and time to build as non-variadic tuple.  That's unfortunate, but at least it rules out tuple as the culprit.   FWIW, I'm going to try to start engaging with NVIDIA's compiler team on this issue.  I should've done that all along.

**Comment by jaredhoberock** [comment]
Yes, the implementation is "iterative" now, I guess. `tuple` is not defined recursively, but some of the associated functionality is -- `tuple_element`, for example. I don't know of any other technique that would avoid recursion.

**Comment by andrewcorrigan** [comment]
libc++ looks to be doing the same thing.  So your implementation is at least as good.  The changes you've made over the past week are already a dramatic improvement over the previous variadic tuple.  I can actually compile CUDA code without running out of memory-- still takes forever, but it does eventually finish.

Moreover, this new tuple gives a dramatic improvement in runtime performance -- 50% for my code, as compared to the non-variadic tuple in Thrust.  This new tuple rocks.

**Comment by andrewcorrigan** [comment]
Closing...
